# Generated by Django 5.0.1 on 2024-02-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
