# Generated by Django 5.0.1 on 2024-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_alter_feedback_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=40)),
                ('user', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
