# Generated by Django 5.0.1 on 2024-02-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0003_signup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='customer',
        ),
    ]
