# Generated by Django 5.0.1 on 2024-02-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0004_alter_signup_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_user', models.CharField(max_length=40)),
                ('supplier_password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
