# Generated by Django 5.0.1 on 2024-02-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0005_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
