# Generated by Django 5.0.1 on 2024-02-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0006_delete_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
