# Generated by Django 5.0.1 on 2024-02-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0008_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_user', models.CharField(max_length=40)),
                ('Customer_password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
