# Generated by Django 5.0.1 on 2024-02-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0009_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_password',
            new_name='customer_password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_user',
            new_name='customer_user',
        ),
    ]
