# Generated by Django 5.0.1 on 2024-02-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0010_rename_customer_password_customer_customer_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
