# Generated by Django 5.0.1 on 2024-02-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0011_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60)),
                ('customer_address', models.CharField(max_length=90)),
                ('customer_contact', models.CharField(max_length=14)),
                ('customer_mail', models.CharField(max_length=60)),
                ('customer_user', models.CharField(max_length=40)),
                ('customer_password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
