# Generated by Django 5.0.1 on 2024-02-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0012_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
