# Generated by Django 5.0.1 on 2024-02-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0013_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=60)),
                ('supplier_address', models.CharField(max_length=90)),
                ('supplier_contact', models.CharField(max_length=14)),
                ('supplier_mail', models.CharField(max_length=60)),
                ('supplier_comp_name', models.CharField(max_length=60)),
                ('supplier_comp_address', models.CharField(max_length=90)),
                ('supplier_comp_mail', models.CharField(max_length=60)),
                ('supplier_comp_bank', models.CharField(max_length=40)),
                ('supplier_comp_acc', models.CharField(max_length=20)),
                ('supplier_user', models.CharField(max_length=40)),
                ('supplier_password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
