# Generated by Django 5.0.1 on 2024-02-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0014_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_price', models.CharField(max_length=90)),
                ('product_category', models.CharField(max_length=14)),
                ('product_unit', models.CharField(max_length=60)),
                ('product_quantity', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
