# Generated by Django 5.0.1 on 2024-02-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
