# Generated by Django 5.0.1 on 2024-02-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0018_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('customer_name', models.CharField(max_length=60)),
                ('customer_address', models.CharField(max_length=90)),
                ('customer_mobile', models.CharField(max_length=14)),
                ('product_id', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=9)),
                ('product_Qty', models.CharField(max_length=4)),
                ('order_total', models.CharField(max_length=5)),
                ('order_date', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
