# Generated by Django 5.0.1 on 2024-02-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0019_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=5)),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=9)),
                ('product_Qty', models.CharField(max_length=4)),
                ('add_stock', models.CharField(max_length=5)),
                ('Stock_date', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
