# Generated by Django 5.0.1 on 2024-02-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0020_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_Qty',
            new_name='product_unit',
        ),
    ]
